config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    # admin dashboard
    get '', to: 'dashboard#index', as: '/'
      # resources
			resources :articles
      # devise
      devise_for :users, controllers: { sessions: 'admin/users/sessions', registrations: 'admin/users/registrations'}
  end

  scope module: 'movie_data', path: 'movie_data' do

    # root
    root "movies#index"
    get 'genre/:gen', to: 'genres#index', as: :genre

    # scoped resources movie_data
    resources :movies
    resources :actors, only: [:index, :show]
    resources :directors, only: [:index, :show]
    resources :genres, only: [:index]

  end

  # articles index and show user resources
  resources :articles, only: [:index, :show]

end

app/models/article.rb
class Article < ApplicationRecord
  before_save :update_published_at
  before_save :update_unpublished_at

  # assosiations
  belongs_to :user
  belongs_to :category
  belongs_to :category, inverse_of: :articles

  # validations
  validates_presence_of :title
  validates_presence_of :content

  # scopes
   scope :published, -> { where(published: true) }
   scope :unpublished, -> { where(published: false) }
   scope :most_recent, -> { order(published_at: :desc) }


  # methods
  def update_published_at
    self.published_at = Time.now if published == true
  end

  def update_unpublished_at
    self.published_at = nil if published == false
  end

end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin_user!

  def index
    if params[:category].blank?
      @articles = Article.all.most_recent
    else
      @articles = category_attributes.published.most_recent
    end
  end

  def show
  end

  def new
    @article = Article.new
  end

  def create
    # user assosiation must be made.
    @article = current_admin_user.articles.new(article_params)

    if @article.save
      redirect_to admin_articles_url, notice: 'Article was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      redirect_to admin_articles_url, notice: 'Article was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @article.destroy
    redirect_to admin_articles_url, notice: 'Article was successfully destroyed.'
  end

  # find all categorys matching id
  def category_attributes
    @category_id = Category.find_by(name: params[:category]).id
    articles = Article.where(category_id: @category_id)
    return articles
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

  def article_params
    params.require(:article).permit(:title, :image, :content, :published, :published_at, :category_id)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    if params[:category].blank?
      @articles = Article.all.most_recent.paginate(:page => params[:page], :per_page => 1)
    else
      @articles = category_attributes.published.most_recent.paginate(:page => params[:page], :per_page => 1)

    end
  end

  def show
    @article = Article.find(params[:id])
    @author = User.find_by(id: @article.user_id)
    # used for back button redirect to catagorys instead of articles.
    @article_category = Category.where(id: @article.category_id)
  end

  # find all categorys matching id
  def category_attributes
     @category_id = Category.find_by(name: params[:category]).id
     articles = Article.where(category_id: @category_id)
     return articles
   end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/admin/articles/_form.html.erb
<%= form_for([:admin,@article]) do |f| %>

    <% if @article.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@article.errors.count, 'error') %> prohibited this Article from being saved:</h2>
        <ul class="list-unstyled">
        <% @article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field row-2 left">
      <%= f.label :title %><br>
      <%= f.text_field :title, class: "form-control" %>
      <br>

      <%= f.label :image %><br>
      <%= f.text_field :image, class: "form-control" %>
      <br>

      <%= f.label :published %><br>
      <%= f.check_box :published, class: "form-control" %>
      <br>

      <%= f.label :categories %><br>
      <%= f.collection_select(:category_id, Category.all, :id, :name) %><br>
      <br>

      <%= f.submit %>
    </div>

    <div class="field row-2 right">
      <%= f.text_area :content, class: "form-control" %>
      <br>

    </div>

<% end %>

app/views/admin/articles/edit.html.erb
<h3 class="center">Edit Article</h3>
<%= render 'form', article: @article %>

app/views/admin/articles/index.html.erb
<%= render 'admin/partials/aside' %>
<header class="admin article-index-header">
  <h1>Listing Articles</h1>
</header>

<br>
<main class="admin">
  <table class="table">
    <thead>
      <tr>
        <th>Title</th>
        <th>Content</th>
        <th>Published</th>
        <th>Published at</th>
        <th>Category</th>
        <th>show</th>
      <th>edit</th>
      <th>delete</th>
  </tr>
    </thead>
    <tbody>
      <% @articles.each do |article| %>
      <tr>
        <td><%= link_to article.title, admin_article_path(article) %></td>
        <td><%= truncate(article.content, length: 50) %></td>
        <td><%= article.published %></td>
        <td><%= article.published_at.strftime("%A, %y, %B, %Y") %></td>
        <td><%= article.category_id %></td>
        <td><%= link_to 'Show', admin_article_path(article), class: '' %></td>
        <td><%= link_to 'Edit', edit_admin_article_path(article), class: '' %></td>
        <td><%= link_to 'Delete', admin_article_path(article), method: :delete, data: { confirm: 'Are you sure?' }, class: '' %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

</main>

app/views/admin/articles/new.html.erb
<h3 class='center'>Create Article</h3>
<%= render 'form', article: @article %>

app/views/admin/articles/show.html.erb
<div>
  <dl class="row">
    <dt class="col-sm-3">Title:</dt>
    <dd class="col-sm-9"><%= @article.title %></dd>
  </dl>
  <dl class="row">
    <dt class="col-sm-3">Image:</dt>
    <dd class="col-sm-9"><%= @article.image %></dd>
  </dl>
  <dl class="row">
    <dt class="col-sm-3">Content:</dt>
    <dd class="col-sm-9"><%= @article.content %></dd>
  </dl>
  <dl class="row">
    <dt class="col-sm-3">Published:</dt>
    <dd class="col-sm-9"><%= @article.published %></dd>
  </dl>
  <dl class="row">
    <dt class="col-sm-3">Published At:</dt>
    <dd class="col-sm-9"><%= @article.published_at %></dd>
  </dl>
  <dl class="row">
    <dt class="col-sm-3">Category:</dt>
    <dd class="col-sm-9"><%= @article.category_id %></dd>
  </dl>
</div>

<div class="link-button link-button--info">
  <%= link_to 'Edit', edit_admin_article_path(@article) %>
</div>
<div class="link-button link-button--info">
  <%= link_to 'Back', admin_articles_path %>
</div>