config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    # admin dashboard
    get '', to: 'dashboard#index', as: '/'
      # resources
			resources :articles
      # devise
      devise_for :users, controllers: { sessions: 'admin/users/sessions', registrations: 'admin/users/registrations'}
  end

  scope module: 'movie_data', path: 'movie_data' do

    # root
    root "movies#index"
    get 'genre/:gen', to: 'genres#index', as: :genre

    # scoped resources movie_data
    resources :movies
    resources :actors, only: [:index, :show]
    resources :directors, only: [:index, :show]
    resources :genres, only: [:index]

  end

  # articles index and show user resources
  resources :articles, only: [:index, :show]

end

app/models/article.rb
class Article < ApplicationRecord
  before_save :update_published_at
  before_save :update_unpublished_at

  # assosiations
  belongs_to :user
  belongs_to :category
  belongs_to :category, inverse_of: :articles

  # validations
  validates_presence_of :title
  validates_presence_of :content

  # scopes
   scope :published, -> { where(published: true) }
   scope :unpublished, -> { where(published: false) }
   scope :most_recent, -> { order(published_at: :desc) }


  # methods
  def update_published_at
    self.published_at = Time.now if published == true
  end

  def update_unpublished_at
    self.published_at = nil if published == false
  end

end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin_user!

  def index
    if params[:category].blank?
      @articles = Article.all.most_recent
    else
      @articles = category_attributes.published.most_recent
    end
  end

  def show
  end

  def new
    @article = Article.new
  end

  def create
    # user assosiation must be made.
    @article = current_admin_user.articles.new(article_params)

    if @article.save
      redirect_to admin_articles_url, notice: 'Article was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      redirect_to admin_articles_url, notice: 'Article was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @article.destroy
    redirect_to admin_articles_url, notice: 'Article was successfully destroyed.'
  end

  # find all categorys matching id
  def category_attributes
    @category_id = Category.find_by(name: params[:category]).id
    articles = Article.where(category_id: @category_id)
    return articles
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

  def article_params
    params.require(:article).permit(:title, :image, :content, :published, :published_at, :category_id)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    if params[:category].blank?
      @articles = Article.all.most_recent.paginate(:page => params[:page], :per_page => 1)
    else
      @articles = category_attributes.published.most_recent.paginate(:page => params[:page], :per_page => 1)

    end
  end

  def show
    @article = Article.find(params[:id])
    @author = User.find_by(id: @article.user_id)
    # used for back button redirect to catagorys instead of articles.
    @article_category = Category.where(id: @article.category_id)
  end

  # find all categorys matching id
  def category_attributes
     @category_id = Category.find_by(name: params[:category]).id
     articles = Article.where(category_id: @category_id)
     return articles
   end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/index.html.erb
<br>
<main class="articles">
  <% @articles.limit(2).each do |article| %>
      <% if article.image.present? %>
        <div class="row-2 center">
            <%= image_tag(article.image, :class => "article-index-image") %>
          <h3 class="center"><%= link_to article.title, article_path(article) -%></h3>
            <div class="byline">
              published: <%= article.published_at.strftime("%A, %y, %B, %Y")%>
            </div>
        </div>
      <% end %>
    <% end %>
</main>
<%= will_paginate @articles %>

app/views/articles/show.html.erb
<style>
  .hero.article-show-image{
    background-image: url("<%= @article.image %>");
    background-repeat: no-repeat;
    background-size: cover;
  }
</style>

<header class="article-show-header">
  <div class="hero article-show-image">
    <h1><%= @article.title %></h1>
  </div>
</header>

<main class="article-show-main">
  <div class="content">
     <%= markdown(@article.content) %>
  </div>
</main>

<div class="link-button link-button--info">
  <%= link_to 'Back', articles_path(category: @article_category.first.name) %>
</div>