config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    # admin dashboard
    get '', to: 'dashboard#index', as: '/'
      # resources
			resources :articles
      # devise
      devise_for :users, controllers: { sessions: 'admin/users/sessions', registrations: 'admin/users/registrations'}
  end

  scope module: 'movie_data', path: 'movie_data' do

    # root
    root "movies#index"
    get 'genre/:gen', to: 'genres#index', as: :genre

    # scoped resources movie_data
    resources :movies
    resources :actors, only: [:index, :show]
    resources :directors, only: [:index, :show]
    resources :genres, only: [:index]

  end

  # articles index and show user resources
  resources :articles, only: [:index, :show]

end

app/models/actor.rb
class Actor < ApplicationRecord

  # movies assosiation through actor_records.
  has_many :actor_records
  has_many :movies, through: :actor_records

  # charactor assosiation through character_records.
  has_many :character_records
  has_many :characters, through: :character_records

  # picture assosiation through imageable pollymorphic assosiation.
  has_many :pictures, :as => :imageable

  
end

app/models/actor_record.rb
class ActorRecord < ApplicationRecord
  belongs_to :movie
  belongs_to :actor
end

app/models/article.rb
class Article < ApplicationRecord
  before_save :update_published_at
  before_save :update_unpublished_at

  # assosiations
  belongs_to :user
  belongs_to :category
  belongs_to :category, inverse_of: :articles

  # validations
  validates_presence_of :title
  validates_presence_of :content

  # scopes
   scope :published, -> { where(published: true) }
   scope :unpublished, -> { where(published: false) }
   scope :most_recent, -> { order(published_at: :desc) }


  # methods
  def update_published_at
    self.published_at = Time.now if published == true
  end

  def update_unpublished_at
    self.published_at = nil if published == false
  end

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :articles
end

app/models/character.rb
class Character < ApplicationRecord

  # actor assosiation through character_records.
  has_many :character_records
  has_many :actors, through: :character_records

  # scope movie_name
  scope :filter_character, -> (name) { where(movie_name: name) }

end

app/models/character_record.rb
class CharacterRecord < ApplicationRecord
  belongs_to :character
  belongs_to :actor
end

app/models/director.rb
class Director < ApplicationRecord
  has_many :director_records
  has_many :movies, through: :director_records
end

app/models/director_record.rb
class DirectorRecord < ApplicationRecord
  belongs_to :movie
  belongs_to :director
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :genre_records
  has_many :movies, through: :genre_records

end

app/models/genre_record.rb
class GenreRecord < ApplicationRecord
  belongs_to :movie
  belongs_to :genre
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :imageable, :polymorphic => true 

  belongs_to :movie
  belongs_to :actor
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :actor_records
  has_many :actors, through: :actor_records

  has_many :genre_records
  has_many :genres, through: :genre_records

  has_many :director_records
  has_many :directors, through: :director_records

  has_many :pictures, :as => :imageable
  
# form genre
  def genre_list
    genres.map(&:name).join(', ')
  end

  def genre_list=(names)
    self.genres = names.split(',').map do |n|
      Genre.where(name: n.strip).first_or_create!
    end
  end

# form actor
  def actor_list
    actors.map(&:name).join(', ')
  end

  def actor_list=(names)
    self.actors = names.split(',').map do |n|
      Actor.where(name: n.strip).first_or_create!
    end
  end

# form director
  def director_list
    directors.map(&:name).join(', ')
  end

  def director_list=(names)
    self.directors= names.split(',').map do |n|
      Director.where(name: n.strip).first_or_create!
    end
  end

end

app/models/picture.rb
class Picture < ApplicationRecord

  # scopt the page_type for movie poster or artwork
  scope :type, -> (name) { where(page_type: name) }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:login]

  # Virtual attribute for authenticating by either username or email
  # This is in addition to a real persisted field like 'username'
  attr_accessor :login

  has_many :articles

  validate :validate_username

  # sign in with email or username
  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_hash).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_hash).first
    end
  end


  # validate username, stop emails and username confusion
  def validate_username
    if User.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end

end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/directors_helper.rb
module DirectorsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/admin/partials/_aside.html.erb
<aside class="admin">
  <h2>admin</h2>
    <!--Start Nav Buttons-->
    <ul>

      <!--Home-->
      <li>
        <i class="material-icons md-18">home</i>
        <%= link_to "dashboard", admin_path %>
      </li>
      <li>
        <%= link_to "articles", admin_articles_path %>
      </li>
      <li>
        <% if current_page?(admin_articles_path) %>
          <%= link_to "create article", new_admin_article_path %>
        <% end %>
      </li>
      <!--End Nav Buttons-->
      <li>
        <%= link_to "edit profile", edit_admin_user_registration_path %>
      </li>
      <!--End Edit Profile-->
    </ul>
</aside>

app/views/layouts/_flashmessages.html.erb
<% flash.each do |name, msg| %>
  <%= content_tag(:div, msg, :id=>"#{name}", :class=> "flash") %>
<%end%>

app/views/layouts/_nav.html.erb
<nav>
  <div class="logo">
    my blog
  </div>
  <ul>
    <li><%= nav_link "movies", root_path %></li>
    <!--Start Categorys-->
    <% Category.all.each do |category| %>
      <li>
        <%= nav_link category.name, articles_path(category: category.name) %>
      </li>
    <% end %>
    <!--Start Admin -->
    <li><%= nav_link "admin", admin_path %></li>
    <% if admin_user_signed_in? %>
      <li><%= link_to "sign-out", destroy_admin_user_session_path, method: :delete %></li>
    <% else %>
      <li><%= nav_link "sign-in", new_admin_user_session_path %></li>
      <li><%= nav_link "sign-up", new_admin_user_registration_path %></li>
    <% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <%= csrf_meta_tags %>
</head>
  <body>
    <%= render 'layouts/nav' %>
    <%= render 'layouts/flashmessages' %>
    <% unless params[:controller].split("/").first == "admin" %>
      <div class="container">
        <%= yield %>
      </div>
    <% else %>
      <div class="container-admin">
        <%= yield %>
      </div>
    <% end %>

  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/welcome.html.erb
<h1>Pages#welcome</h1>
<p>Find me in app/views/pages/welcome.html.erb</p>