config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    # admin dashboard
    get '', to: 'dashboard#index', as: '/'
      # resources
			resources :articles
      # devise
      devise_for :users, controllers: { sessions: 'admin/users/sessions', registrations: 'admin/users/registrations'}
  end

  scope module: 'movie_data', path: 'movie_data' do

    # root
    root "movies#index"
    get 'genre/:gen', to: 'genres#index', as: :genre

    # scoped resources movie_data
    resources :movies
    resources :actors, only: [:index, :show]
    resources :directors, only: [:index, :show]
    resources :genres, only: [:index]

  end

  # articles index and show user resources
  resources :articles, only: [:index, :show]

end

app/controllers/movie_data/actors_controller.rb
class MovieData::ActorsController < ApplicationController
  before_action :set_actor, only: [:show, :edit, :update, :destroy]

  # GET /actors
  # GET /actors.json
  def index
    @actors = Actor.all.paginate(:page => params[:page], :per_page => 10)
  end

  # GET /actors/1
  # GET /actors/1.json
  def show
    @actor_movies = @actor.movies
  end

  # GET /actors/new
  def new
    @actor = Actor.new
  end

  # GET /actors/1/edit
  def edit
  end

  # POST /actors
  # POST /actors.json
  def create
    @actor = Actor.new(actor_params)

    respond_to do |format|
      if @actor.save
        format.html { redirect_to @actor, notice: 'Actor was successfully created.' }
        format.json { render :show, status: :created, location: @actor }
      else
        format.html { render :new }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /actors/1
  # PATCH/PUT /actors/1.json
  def update
    respond_to do |format|
      if @actor.update(actor_params)
        format.html { redirect_to @actor, notice: 'Actor was successfully updated.' }
        format.json { render :show, status: :ok, location: @actor }
      else
        format.html { render :edit }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /actors/1
  # DELETE /actors/1.json
  def destroy
    @actor.destroy
    respond_to do |format|
      format.html { redirect_to actors_url, notice: 'Actor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_actor
      @actor = Actor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def actor_params
      params.require(:actor).permit(:name)
    end
end

app/controllers/movie_data/directors_controller.rb
class MovieData::DirectorsController < ApplicationController
  before_action :set_director, only: [:show, :edit, :update, :destroy]

  # GET /directors
  # GET /directors.json
  def index
    @directors = Director.all.paginate(:page => params[:page], :per_page => 10)
  end

  # GET /directors/1
  # GET /directors/1.json
  def show
  end

  # GET /directors/new
  def new
    @director = Director.new
  end

  # GET /directors/1/edit
  def edit
  end

  # POST /directors
  # POST /directors.json
  def create
    @director = Director.new(director_params)

    respond_to do |format|
      if @director.save
        format.html { redirect_to @director, notice: 'Director was successfully created.' }
        format.json { render :show, status: :created, location: @director }
      else
        format.html { render :new }
        format.json { render json: @director.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /directors/1
  # PATCH/PUT /directors/1.json
  def update
    respond_to do |format|
      if @director.update(director_params)
        format.html { redirect_to @director, notice: 'Director was successfully updated.' }
        format.json { render :show, status: :ok, location: @director }
      else
        format.html { render :edit }
        format.json { render json: @director.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /directors/1
  # DELETE /directors/1.json
  def destroy
    @director.destroy
    respond_to do |format|
      format.html { redirect_to directors_url, notice: 'Director was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_director
      @director = Director.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def director_params
      params.require(:director).permit(:name)
    end
end

app/controllers/movie_data/genres_controller.rb
class MovieData::GenresController < ApplicationController

  def index
    if params[:gen]
      @genre_id = Genre.find_by(id: params[:gen]).name
      @genres = Genre.where(name: @genre_id).paginate(:page => params[:page], :per_page => 18)
    else
      @genres = Genre.all.paginate(:page => params[:page], :per_page => 18)
    end
  end

end

app/controllers/movie_data/movies_controller.rb
class MovieData::MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all.paginate(:page => params[:page], :per_page => 18)
  end

  # GET /movies/1
  def show
    @genres = @movie.genres.all
    @actors = @movie.actors.all
    @directors = @movie.directors.all

    # scoped movie and art work images.
    @poster = Picture.where(imageable_id: @movie.id).type("poster")
    @artwork = Picture.where(imageable_id: @movie.id).type("artwork")

  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :date, :description, :image, :byline, :iframe, :genre_list, :actor_list, :director_list)
    end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movie_data/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field row-2">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
    <br>
    <%= f.label :date %><br>
    <%= f.text_field :date %>
    <br>
    <%= f.label :genre, "Genre - Comma seperated list."%><br>
    <%= f.text_field :genre_list %>
    <br>
    <%= f.label :actor, " Actors - Comma seperated list."%><br>
    <%= f.text_field :actor_list %>
    <br>
    <%= f.label :directors, " Directors - Comma seperated list."%><br>
    <%= f.text_field :director_list %>
    <br>
    <%= f.label :image %><br>
    <%= f.text_field :image %>
    <br>
    <%= f.label :byline %><br>
    <%= f.text_field :byline %>
    <br>
    <%= f.label :trailer%><br>
    <%= f.text_field :iframe%>
    <br>
    <%= f.submit %>
  </div>

  <div class="field row-2">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  
<% end %>

app/views/movie_data/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movie_data/movies/index.html.erb
<!--Main Begin-->
<main>

  <!--Movie Items -->
  <% @movies.each do |movie| %>
      <article class="movie-index-article">

        <!--Image-->
        <div ="movie-index-img-wrapper">
          <% movie.pictures.type("poster").each do |poster| %>
          <% if poster.link_address.present? %>
                <%= image_tag(poster.link_address) %>
              <% end %>
            </div>
            <!--Title-->
            <%= link_to movie.title, movie_path(movie) %>
          <% end %>

      </article>

  <% end %>
</main>
<%= will_paginate %>

app/views/movie_data/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Back', movies_path %>

app/views/movie_data/movies/show.html.erb
  <!--Begin Poster -->
<header class="movie-show-header">
  <div class="movie-show-poster row-2">
    <% @poster.each do |image| %>
      <%= image_tag(image.link_address, class: "movie-show-image") %>
    <% end %>
  </div>

  <!--Begin Movie info-->
  <div class="movie-show-info row-2">

    <h3 class="center"><%= @movie.title %></h3>

    <p>
      <strong>Release Date:</strong>
      <%= @movie.date %>
    </p>

    <p>
      <strong>Actor:</strong>
      <% @actors.each do |actor| %>
        <%= link_to actor.name, actor_path(actor) %>,
      <% end %>
    </p>

    <p>
      <strong>Director:</strong>
      <% @directors.each do |dir| %>
        <%= link_to dir.name, director_path(dir) %>,
      <% end %>
    </p>

    <p>
      <strong>Byline:</strong>
      <%= @movie.byline %>
    </p>

    <p>
      <strong>Genres:</strong>
      <% @genres.each do |genre| %>
        <%= link_to genre.name, genres_path(gen: genre) %>,
      <% end %>
    </p>
  </div>
</header>


<main class="movie-show">

    <!--Begin Iframe -->
    <div class="iframe-wrapper">

      <div class="aspect-ratio">
          <iframe src="<%= @movie.iframe %>" frameborder="0" frameborder="0" allowfullscreen></iframe>
      </div>


    </div>
    <!--Begin Artwork -->
    <div class="artwork-wrapper row-1">

      <% @artwork.limit(6).each do |art| %>
        <div class="artwork row-3">

          <% unless art.link_address.nil? %>
            <%= image_tag(art.link_address) %>
          <% end %>

        </div>
      <% end %>
    </div>
  <br>

</main>


<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %> |